# Enable the build cache to save time by reusing outputs produced by other successful builds.
# https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching=true
# Enable the configuration cache to reuse the build configuration and enable parallel task execution.
# (Note that some plugins may not yet be compatible with the configuration cache.)
# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
kotlin.code.style=official
# Maven Central
SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
# Dummy properties so that anyone can compile the library
mavenCentralUsername=""
mavenCentralPassword=""
# Maven Publish
GROUP=info.metadude.kotlin.library.schedule
POM_ARTIFACT_ID=schedule
VERSION_NAME=1.0.0
VERSION_VCS_TAG=v1.0.0
VERSION_DESCRIPTION=Initial publication.
POM_NAME=Schedule
POM_DESCRIPTION=A Kotlin library containing a parser, models, and repositories for conference schedule APIs.
POM_URL=https://github.com/EventFahrplan/schedule
POM_SCM_URL=https://github.com/EventFahrplan/schedule
POM_SCM_CONNECTION=scm:git:git://github.com/EventFahrplan/schedule.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/EventFahrplan/schedule.git
POM_INCEPTION_YEAR=2026
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=https://github.com/EventFahrplan/schedule/LICENSE.txt
POM_LICENCE_DIST=repo
POM_DEVELOPER_ID=johnjohndoe
POM_DEVELOPER_NAME=Tobias Preuss
